# Copyright © 2026, Alexandre Coderre-Chabot.
#
# This file is part of Lector (https://github.com/acodcha/lector), a C++ library for parsing command
# line arguments. Lector is licensed under the MIT License (https://mit-license.org).
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
# associated documentation files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge, publish, distribute,
# sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# - The above copyright notice and this permission notice shall be included in all copies or
#   substantial portions of the Software.
# - THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
#   BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
#   DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM
#   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
name: macOS
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
# This is needed for std::from_chars on macOS.
env:
  MACOSX_DEPLOYMENT_TARGET: "13.3"
jobs:
  build_and_test_bazel_macos:
    name: Bazel
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: Print the C++ version
        run: c++ --version
      - name: Print the Bazel version
        run: bazel --version
      - name: Build with Bazel
        run: bazel build //... --macos_minimum_os=13.3
      - name: Test with Bazel
        run: bazel test //... --macos_minimum_os=13.3
  build_and_test_cmake_macos:
    name: CMake
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Print the C++ version
        run: c++ --version
      - name: Print the CMake version
        run: cmake --version
      - name: Configure with CMake
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release -D LECTOR_TEST=ON
      - name: Build with CMake
        run: cmake --build build --config Release --parallel
      - name: Test with CMake
        run: ctest --test-dir build -C Release
  build_and_test_meson_macos:
    name: Meson
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Meson and Ninja
        run: brew install meson ninja
      - name: Print the C++ version
        run: c++ --version
      - name: Print the Meson version
        run: meson --version
      - name: Print the Ninja version
        run: ninja --version
      - name: Create the Meson subprojects directory
        run: mkdir subprojects
      - name: Download the Meson wrap for GoogleTest
        run: meson wrap install gtest
      - name: Configure with Meson
        run: meson setup build
      - name: Build with Meson
        run: meson compile -C build
      - name: Test with Meson
        run: meson test -C build
